---
 - name: remove nfs server configurations
   hosts: ip-172-31-28-121.ec2.internal
   tasks:

    - name: remove nfs software
      dnf:
       name: nfs-utils
       state: absent

    - name: remove directory
      file:
       path: /share100
       state: absent

 - name: remove nfs mount and nfs client
   hosts: ip-172-31-21-170.ec2.internal
   tasks:

    - name: umount the share                
      mount:
       src: ip-172-31-28-121.ec2.internal:/share100
       path: /mnt
       state: absent  
       fstype: nfs

    - name: remove nfs software
      dnf: 
       name: nfs-utils
       state: absent
...